config/routes.rb
Rails.application.routes.draw do
  post 'add/user', to: 'rooms#add_user'
  resources :rooms do
    resources :messages
  end
  root "rooms#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit :broadcast_room_messages_create
  after_update_commit :broadcast_room_messages_update
  after_destroy_commit :broadcas_room_messages_destroy

  private
  def broadcast_room_messages_create
    broadcast_append_to('room_messages_channel', partial: 'messages/message', locals: { message: self }, target: "room_messages_div")
  end

  def broadcast_room_messages_update
    broadcast_replace_to('room_messages_channel', partial: 'messages/message', locals: { message: self }, target: "message_#{id}")
  end

  def broadcas_room_messages_destroy
    broadcast_remove_to('room_messages_channel', target: "message_#{id}")
  end

end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true

  has_many :user_rooms
  has_many :users, through: :user_rooms
  has_many :messages

  after_update_commit :update_room_details
  private
  def update_room_details
    broadcast_replace_to('room_details_channel', partial: 'shared/room', locals: { room: self }, target: "room_#{self.id}")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :messages
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_commit on: :create do
    broadcast_append_to('users_rooms_channel', partial: 'shared/room', locals: { room: Room.find(room_id) }, target: "user_#{user_id}_rooms")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[create edit]
  before_action :set_message, only: %i[edit update destroy]

  def create
    @message = @room.messages.new(message_params)
    @message.user = current_user

    respond_to do |format|
      if @message.save
        format.turbo_stream
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @message.update message_params
        format.turbo_stream
      end
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to room_path(@message.room), notice: "Message was successfully destroyed." }
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:message)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[ show edit update destroy ]


  def index
    @rooms = Room.all
  end


  def show
  end


  def new
    @room = Room.new
  end


  def edit
  end


  def create
    @room = Room.new(room_params)
    respond_to do |format|
      if @room.save
        UserRoom.create(room: @room, user: current_user)
        format.turbo_stream { render turbo_stream: turbo_stream.append('rooms', partial: 'shared/room', locals: { room: @room }) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('room_form', partial: 'rooms/form', locals: { room: @room }) }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update room_params
        format.turbo_stream { render turbo_stream: turbo_stream.replace("room_#{@room.id}", partial: 'shared/room', locals: { room: @room }) }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @room.destroy
  end

  def add_user

    UserRoom.create(room_id: params[:room_id], user_id: params[:user_id])

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace("room_show#{params[:room_id]}", partial: 'rooms/room', locals: { room: Room.find(params[:room_id]) }) }
    end
  end


  private

    def set_room
      @room = Room.find(params.expect(:id))
    end
  end

    def room_params
      params.expect(room: [ :name ])
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Chat App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="https://cdn.tailwindcss.com"></script>
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

      <%= yield %>
   
  </body>
</html>

app/views/messages/_form.html.erb
<div data-controller="form">
  <%= form_with(model: [room, message], id: 'message_form', class: 'w-full flex flex-col', data: { controller: 'form', action: 'submit->form#resetComponent' }) do |f| %> 
    <div class="flex flex-col gap-3">
      <%= f.text_field :message, class: 'w-full border-2 border-gray-200 rounded p-2' %>
      <%= f.submit 'Send', class: 'cursor-pointer p-2 text-sm text-white font-semibold bg-green-600 rounded' %>
    </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<%= turbo_frame_tag "message_#{message.id}", class: 'bg-gray-200 px-3 py-2 flex justify-between rounded items-center gap-2 shadow' do%>
<div class="flex gap-1">
  <span class="text-gray-600 text-sm"> <%= message.user.email  %></span>
  <span class="font-semibold text-sm"> <%= message.message %></span>
</div>
<div class="flex gap-3">
  <%= link_to edit_room_message_path(message, room_id: message.room ), class: 'text-sm font-medium bg-sky-800 text-white py-1 px-3 rounded' do %>
    Edit
  <% end %>
  <%= button_to room_message_path(message.room, message), class: 'text-sm font-medium bg-red-800 text-white py-1 px-3 rounded', method: :delete do %>
    Delete
  <% end %>
</div>
<% end %>

app/views/messages/edit.html.erb
 <%= turbo_frame_tag "message_#{@message.id}", class: 'bg-gray-200 px-3 py-2 flex justify-between rounded items-center gap-2 shadow' do%>


    <%= render 'messages/form', { room: @room, message: @message } %>
    

<% end %>

app/views/rooms/_form.html.erb
<h4 class="text-base font-medium text-white text-center"> Room</h4>
<div data-controller="form">
  <%= form_with(model: room,
                class: "flex flex-col my-3 w-full", 
                data: { controller: 'form', action: 'submit->form#resetComponent' }) do |form| %>
    <% if room.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

        <ul>
          <% room.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="flex flex-col gap-1 justify-center">
      <%= form.label :name, class: 'text-white font-semibold text-sm' %>
      <%= form.text_field :name, class: "w-full rounded border border-gray-200 font-semibold text-xs" %>
    </div>

    <div class="flex mt-2 gap-2 justify-end">
      <%= form.submit class: "cursor-pointer p-2 text-sm text-white font-semibold bg-green-600 rounded" %>
      <%= link_to  'Cancel', rooms_path, class: 'cursor-pointer p-2 text-sm text-white font-semibold bg-red-600 rounded'%>
    </div>
  <% end %>
</div>

app/views/rooms/_room.html.erb
<section class="flex flex-col gap-2 mt-10 items-center justify-center" id="room_show<%= "#{ room.id }" %>">
  <div class="flex flex-col">
    <h3 class="font-bold text-3X1 text-white"> <%= room.name  %>  - Room </h3>
    <span class="text-white font-semibold">Users in  this room: </span>
  </div>

  <section class="flex gap-5 items-center justify-center">
    <div class="py-2 px-10 flex flex-col gap-1 items-center border-sky-600 border rounded-lg my-2 shadow-lg w-96">
      <h3 class="text-white font-semibold text-center">Users in this room</h3>
      <% User.all.each do |user| %>
        <% next unless room.users.include?(user)  %>
        <div class="rounded underline text-white my-1 font-semibold text-sm">
          <%= user.email %>
        </div>
      <% end %>
    </div>
    <div class="py-2 px-10 flex flex-col gap-1 items-center border-sky-600 border rounded-lg my-2 shadow-lg w-96">
      <h3 class="text-white font-semibold text-center">All users </h3>
      <% User.all.each do |user| %>
        <% next if room.users.include?(user)  %>
        <%= button_to add_user_path, params: {user_id: user, room_id: room}, id: "add_user_#{user.id}", method: :post do %>
          <div class="rounded underline text-white my-1 font-semibold text-sm">
            <%= user.email %>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>
</section>

app/views/rooms/edit.html.erb
<%= turbo_frame_tag "room_#{@room.id}" do %>
  <div class="mx-auto md:w-2/3 w-full">
    <%= render "form", room: @room %>
  </div>
<% end %>

app/views/rooms/index.html.erb
<%= turbo_frame_tag 'rooms_controller' do %>
  <main class="flex w-full h-screen bg-[#181D31]">
    <%= render 'shared/side_bar' %>
    <section class="flex flex-col items-center justify-center h-full w-full">
        <%= image_tag('chat.png', width: '200') %>
        <h1 class="font-bold text-4xl text-white my-4"> Chat App - Ruby on Rails 8.0 </h1>
        
        <p class="text-center font-semibold text-white"> Welcome! </p>
    </section>
  </main>
<% end %>

app/views/rooms/new.html.erb
<%= turbo_frame_tag 'room_form' do %>
  <h4 class="font-medium text-base text-white text-center"> Create new Room</h4>
  <%= render "form", room: @room %>
<% end %>

app/views/rooms/show.html.erb
<%= turbo_frame_tag 'rooms_controller' do %>
<%= turbo_stream_from 'room_messages_channel' %>
  <main class="flex w-full h-screen bg-[#181D31]">
    <%= render 'shared/side_bar' %>
    <section class="w-5/6 flex flex-col gap-5 h-screen px-5">
      <%= render 'room', room: @room  %>

      <div id="room_messages_div_container" class="flex flex-col items-center justify-center w-full">
      <div class="flex flex-col items-center justify-center w-5/6">
      <div id="room_messages_div" class="h-72 w-5/6 bg-white rounded p-2 overflow-y-auto">
        <% @room.messages.order(created_at: :asc).each do |message| %>
          <%= render 'messages/message', {message: message} %>
        <% end %>
      </div>
      </div>
      <br/>
      <div class="flex flex-col items-center justify-center w-5/6">
        <%= render 'messages/form', { room: @room, message: Message.new } %>
      </div>

    </section>
  </main>
<% end %>

app/views/shared/_create_room.html.erb
<%= turbo_frame_tag 'room_form' do%>
  <section class="flex flex-col items-center justify-center gap-2 mb-5">
    <h3 class="text-white font-semibold text-sm text-center">Want to start a new conversation?</h3>
    <%= link_to new_room_path, id: 'new_room', class: 'px-3 py-1 bg-green-700 text-white font-semibold text-sm' do %>
    Create a new room
    <% end %>
  </section>
<% end %>

app/views/shared/_room.html.erb
<%= turbo_frame_tag "room_#{room.id}" do %>
  <div class="text-white font-semibold text-center">
    <%= link_to room_path(room), class: 'font-semibold text-white text-sm', data: {turbo_frame: 'rooms_controller'} do %>
      <%= room.name %>
    <% end %>
    <%= link_to 'Edit', edit_room_path(room), class: "text-white font-xs"%>
  </div>

<% end %>

app/views/shared/_side_bar.html.erb
<%= turbo_stream_from 'users_rooms_channel' %>
<%= turbo_stream_from 'room_details_channel' %>
<nav class="w-60 flex flex-col items-center justify-between border border-sky-50 ">
  <%= render "shared/user_rooms" %>
  <%= render "shared/create_room" %>

</nav>

app/views/shared/_user_rooms.html.erb
<section class="flex flex-col w-full">
  <span class="text-white text-center font-semibold mt-5">
    <%= current_user.email %>
  </span>
  <div class="flex flex-col items-center justify-center mt-2 w-full">
    <%= button_to 'Log Out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'px-3 py-1 text-white bg-red-700 rounded font-semibold text-sm' %>
  </div>
  <h3 class="text-white font-bold text-xl mt-3 text-center mb-2">My Rooms</h3>
  <div class="flex flex-col -x-5 gap-2 w-full" id="user_<%= current_user.id %>_rooms">
    <% current_user.rooms.all.each do |room| %>
      <%= render 'shared/room', room:room  %>
    <% end %>
  </div>
</section>